name: "bintest"

on:
  pull_request:
    branches: [main]

jobs:
  bintest:
    name: 'bintest new/modified recipes'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - id: files
        name: Get changed files
        uses: tj-actions/changed-files@v20
        with:
          path: pkgs
      - name: Run bintest
        run: |
          for file in ${{ steps.files.outputs.all_modified_files }}; do
            go run github.com/candrewlee14/webman@latest -l "." dev bintest ${file}
          done